### ISSUE TITLE
Artigo

### ISSUE THREAD

**Issue by robersonjfa** [MaickTonet/CallTasks#2]
- De forma geral o artigo precisa ser revisto. Vejam os modelos que disponibilizados
- Estrutura de tópicos sugerida:
**_Título: Trabalho Integrado dos componentes de 
Banco de Dados II, Engenharia de Software I e Programação II

Resumo

1) Introdução
Apresentar a solução/problema
Descrever brevemente como foi desenvolvido
Apresentar a estrutura do artigo

2) Materiais e Métodos
É uma descrição das ferramentas utilizadas e 
de como tudo foi desenvolvido.
Aqui pode ser colocada a parte de modelagem, requisitos, etc, etc

3) Desenvolvimento
Aqui falar do sistema, pode colocar códigos(banco e programação),
podem colocar telas também

4) Conclusão_**

**Comment by MaickTonet** [comment]
O artigo foi atualizado com as devidas normas de formatação, e esta disponível em calltasks/documentos
